name: finalmain
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
      
      - name: Test
        run: go test ./...


  deploy:
      name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      needs: test
  
      steps:
      
        - name: Checkout
          uses: actions/checkout@v4

      
        - name: Set up Docker buildx
          uses: docker/setup-buildx-action@v3

      
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5.5.1
          with:
           images: ruslan272/finalmain

      
        - name: Build and push Docker Image
          uses: docker/build-push-action@v5
          with:
           context: .
           push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
